# Data Set Over View

In [17]:
# import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [18]:
# read the dataset
df=pd.read_excel("C:\\Users\\abc\\Documents\\homeprices.xlsx")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [19]:
# number of rows and columns
df.shape

(5, 4)

In [20]:
# Name of the all the columns of the dataset
for n in df.columns:
    print(n)

area
bedrooms
age
price


In [21]:
# basic about dataset
df.describe()

area  bedrooms       age          price
count     5.000000  4.000000   5.00000       5.000000
mean   3280.000000  3.750000  18.20000  616000.000000
std     540.370243  0.957427   8.01249   83919.604384
min    2600.000000  3.000000   8.00000  550000.000000
25%    3000.000000  3.000000  15.00000  565000.000000
50%    3200.000000  3.500000  18.00000  595000.000000
75%    3600.000000  4.250000  20.00000  610000.000000
max    4000.000000  5.000000  30.00000  760000.000000

In [22]:
# data types of all the columns of the dataset
df.dtypes

area          int64
bedrooms    float64
age           int64
price         int64
dtype: object

# Data Preprocessing (Handle Missing Values)

In [23]:
# extract the bedrooms column of the dataset
df.bedrooms

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [24]:
# median of the bedrooms column of the dataset
df.bedrooms.median()

3.5

In [25]:
# math module import 
import math

In [26]:
# take only whole value
median_bedrooms=math.floor(df.bedrooms.median())

In [27]:
# median_bedrooms variable
median_bedrooms

3

In [28]:
# dataset df
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [29]:
# count all the null values in all the columns
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [30]:
# fill the null values
df.bedrooms=df.bedrooms.fillna(median_bedrooms)

In [31]:
# print df
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [32]:
# initialize the linear regression model
reg=linear_model.LinearRegression()

In [33]:
# print reg variable
reg

LinearRegression()

In [34]:
# extract area column, and make it dataset
df[['area']]

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [46]:
# extract the bedrooms column, and make it dataset
df[['bedrooms']]

bedrooms
0       3.0
1       4.0
2       3.0
3       3.0
4       5.0

In [48]:
# extract the age column, and make it dataset
df[['age']]

age
0   20
1   15
2   18
3   30
4    8

In [67]:
# make the numpy array of the area, bedrooms and age columns datasets
df[['area','bedrooms','age']].values

array([[2.6e+03, 3.0e+00, 2.0e+01],
       [3.0e+03, 4.0e+00, 1.5e+01],
       [3.2e+03, 3.0e+00, 1.8e+01],
       [3.6e+03, 3.0e+00, 3.0e+01],
       [4.0e+03, 5.0e+00, 8.0e+00]])

In [35]:
# make the dataset of the price column and make it numpy array
df[['price']].values

array([[550000],
       [565000],
       [610000],
       [595000],
       [760000]], dtype=int64)

In [78]:
# Lets fit the model
reg.fit(df[['area','bedrooms','age']].values,df[['price']].values)

LinearRegression()

In [ ]:
# lets predict 
reg.predict([[3000,3,40]])  # area=3000,bedrooms=3,age=40

In [79]:
# coefficient
reg.coef_

array([[   137.25, -26025.  ,  -6825.  ]])

In [80]:
# intercept
reg.intercept_

array([383725.])

In [86]:
# price=m1*area + m2*bedrooms + m3*age + b
# m1,m2,m3 are coefficients of area, bedrooms and age variables
# b = intercept
# price is the variable whic we have to find
(137.25*3000) + (-26025.*3) + (-6825.*40) + 383725.

444400.0

Hence, we can say that the model is correct.